# Build phase
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Serve static build to Nginx volume
FROM alpine:3.19
WORKDIR /frontend_build
COPY --from=build /app/dist .
VOLUME ["/frontend_build"]
CMD ["sh", "-c", "cp -r /frontend_build/* /usr/share/nginx/html/ || true"]
