FROM node:20-bookworm

WORKDIR /app
COPY ./frontend/package*.json ./

RUN npm install -g npm@latest \
 && npm cache clean --force \
 && npm install esbuild@latest vite@latest rollup@3 --force

COPY ./frontend/ .
EXPOSE 5173
CMD ["npm", "run", "dev"]
