# Utiliser une image de base avec Java 21 et Maven
FROM maven:3.9.9-eclipse-temurin-21

# Définir le répertoire de travail
WORKDIR /app

# --- PAS DE "COPY" de code source ici ---
# Le code sera monté par docker-compose

# On peut pré-copier le wrapper et les POMs pour mettre en cache les dépendances
# Assurez-vous que mvnw et .mvn sont bien à la racine du projet
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY backend/pom.xml backend/
COPY shared_common/pom.xml shared_common/

# Télécharger les dépendances (cette étape sera mise en cache)
RUN mvn dependency:go-offline -B

# La commande de démarrage est juste un placeholder
# Elle sera ÉCRASÉE par docker-compose
CMD ["./mvnw", "spring-boot:run"]