# Étape 1 : Build React
FROM node:20 AS build
WORKDIR /app

# Copier fichiers de dépendances
COPY ./frontend/package*.json ./

# Générer un lockfile s’il manque, puis installation propre
RUN if [ ! -f package-lock.json ]; then \
      npm install --package-lock-only; \
    fi && \
    npm ci

# Copier le reste du code et builder
COPY ./frontend/ ./
RUN npm run build

# Supprimer toute config existante
RUN rm -rf /etc/nginx/conf.d/*

# Étape 2 : Servir avec Nginx
FROM nginx:stable-alpine
COPY ./frontend/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
