FROM node:20-alpine

WORKDIR /app
COPY package*.json ./

# npm ci automatique
RUN npm install -g npm@latest && npm ci || npm install

COPY ./frontend/ /frontend/

EXPOSE 5173
CMD ["npm", "run", "dev"]
